### PR TITLE
use gopkgs if possible to get packages faster

### PR DESCRIPTION
**Pull request by haya14busa**
Hi, I created https://github.com/haya14busa/gopkgs which list all go packages fast by using the same implementation as [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports).

In my environment ($GOPATH/src has 725045 files...), `:Unite go/import` is slow for daily use, but by introducing `gopkgs`, it takes just a sec.

Can you consider to include it?

I'll add some note for `gopkgs` in README or document if you want.

Thanks

### CODE REVIEW

**Comment by rhysd** [comment]
Nice work!  I'm feeling the same problem explained here.

> I'll add some note for gopkgs in README or document if you want.

I have nothing special to say about that, it's up to you :smile:

**Comment by rhysd** [comment]
It may be a good idea to disable cache when `gopkgs` exists.  I need to try.

**Comment by rhysd** [comment]
@haya14busa 

I added description about gopkgs.  If you feel something lacking, please let me know.  I'll add more.

**Comment by haya14busa** [comment]
Thank you for the merge and documentation! :sparkles:  :bird:

> It may be a good idea to disable cache when gopkgs exists. I need to try.

I agree with you. We might have no need to rely on cache by Vim script.
I think it's easy to implement, but can I ask you to implement it?
But, i'll do it if you want.

**Pull request merged**
